[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
scraper = { workspace = true }
signal-hook.workspace = true

[lib]
name = "common"
path = "src/lib.rs"

